### ISSUE TITLE
can't send code anymore to R-Box

### ISSUE THREAD

**Issue by bnicenboim** [randy3k/R-Box#65] opened 2015-11-21 09:53 UTC
Since today, every time I do control+enter (in Linux) I get:
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "rbox.send_text in /home/bruno/.config/sublime-text-3/Installed Packages/R-Box.sublime-package", line 209, in run
  File "rbox.send_text in /home/bruno/.config/sublime-text-3/Installed Packages/R-Box.sublime-package", line 18, in __init__
KeyError: 'linux'

(I'm using Ubuntu)
Any ideas? It was working perfectly before, I of course tried to uninstall R-box and install it again.

**Comment by randy3k** [comment] 2015-11-21 17:50
The problem is related to the default value of Program. It is fixed now 0ad7c729b387e23bcfebea85bc5bd575267fd5fe. The update will be available in Package Control in a short time. Meanwhile, you can launch `R-Box: Choose Program` to temporary fix the problem.

**Closed by randy3k** 2015-11-21 17:50 UTC

**Comment by bnicenboim** [comment] 2015-11-22 09:44
great, thanks!
