### ISSUE TITLE
RStudio is not supported for current syntax,

### ISSUE THREAD

**Issue by rrodrigueznt** [randy3k/R-Box#100] opened 2017-06-08 12:23 UTC
Hi! Here a happy SendCode/R-Box user!

After experimenting for a while with SendCode and R scripts, I would like to use Sublime Text to author R Markdown documents. Thanks in advance for any help!

After composing a very document in RStudio and publishing it here...

http://rpubs.com/rrodriguez/ggplot2_colors

... I would also like to move its edition to Sublime Text. Thus, I've created a Gist with the same code, opened it in Sublime Text 3, and submitted it by using R-Box > Render Rmd to HTML. And get this error...

![rmarkdown2rstudio error201706081409](https://user-images.githubusercontent.com/1550835/26928129-21368458-4c55-11e7-90c5-5cb195b55a77.png)

SendCode has been previously configured to sending to RStudio. If I select SendCode: Choose REPL Program when the Rmd file is opened, no R GUI or RStudio Desktop options appear. Those are only available to R files.

Please, what am I using wrong? How could I use Sublime Text 3 to edit and render R Markdown scripts? Is it possible?

Thanks for any help!

**Comment by randy3k** [comment] 2017-07-06 19:16
@rrodrigueznt sorry for the long delay. Somehow I have missed this thread. It should be fixed with the latest SendCode.

**Closed** 2017-07-06 19:15 UTC

**Comment by giantwhale** [comment] 2017-07-23 19:08
I am experiencing the same issue.  I am trying to send to rgui, but receive an error saying Rgui is not supported for the current system.

**Comment by randy3k** [comment] 2017-07-23 20:52
it should be fixed in the latest SendCode. Try update SendCode first and let me know if you can still reproduce it.

**Comment by rrodrigueznt** [comment] 2017-08-04 09:23
Randy, please, could you provide me with a working R Markdown example that you can confirm MUST work when sent from SendCode to RStudio? My test code is now travelling nicely from Sublime/RStudio but I'm not able yet to get the output. The same code directly edited with/in RStudio produces a nice output! I would like to debug the problem here: an example working for you will be a great help! Thanks!

**Comment by randy3k** [comment] 2017-08-04 10:23
What do you mean by not getting the output?

**Comment by rrodrigueznt** [comment] 2017-08-04 11:28
Sorry for not being clear! For instance, this code really simple, the one RStudio includes as an example/template when creating a new RMarkdown script, submitted (Knit to PDF) directly at RStudio...

http://portal.idisantiago.es/xwiki/bin/download/R/WebHome/PDFtest.Rmd

.... gives this PDF file...

http://portal.idisantiago.es/xwiki/bin/download/R/WebHome/PDFtest.pdf

If I open the script with Sublime Text and R-Box > Knit Rnw to PDF it, I get this messages...

http://portal.idisantiago.es/xwiki/bin/download/R/WebHome/PDFtest.Rmd.log.txt

... and no PDF is produced. it seems that the intermediary *.tex file is not correct! What I see is a *.tex file similar to the original *.Rmd one. Here it is...

http://portal.idisantiago.es/xwiki/bin/download/R/WebHome/PDFtest.tex

Same box. Please, any idea? Thanks!

**Comment by randy3k** [comment] 2017-08-04 11:47
Because it is a Rmd file but not a Rmw file. I guess you have mixed up Rmarkdowm and RSweave files.


Btw, though the menu only says Rmarkdow to HTML, it is still capable of generating PDF by specifying PDF output in the yank header.

**Comment by rrodrigueznt** [comment] 2017-08-04 12:41
Ummm... I've made a mix during the trials, but I think I'm able to differentiate between Rnw and Rmd files. I'll do my best to clarify the situation and report back in the following few days. Going to use these two files as "case study"...

Rnw file...
http://portal.idisantiago.es/xwiki/bin/download/R/WebHome/SweaveTest.Rnw

Rmd file...
http://portal.idisantiago.es/xwiki/bin/download/R/WebHome/PDFtest.Rmd

I'm getting again the "rstudio is not supported for this syntax error message" when R-Box > Knit or Sweave Rnw files to RStudio from Sublime Text, but perhaps my failure is too obvious. Please, allow me to think a bit about this! Thanks!

Thanks for your time!

**Comment by rrodrigueznt** [comment] 2017-08-04 12:55
Yeap... in fact, if I don't set the syntax, Sublime Text R-Box menu doesn't appear!

**Comment by randy3k** [comment] 2017-08-04 13:07
Ai...there is a bug for Rnw files. Will fix it soon
